global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8080']
  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:8080']
  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:8080']
  - job_name: 'inventory-service'
    static_configs:
      - targets: ['inventory-service:8080']
  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:8080']
  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:8080']
