apiVersion: v2
name: ecommerce-platform
description: E-commerce microservices platform
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: 12.x.x
    repository: https://charts.bitnami.com/bitnami
  - name: redis
    version: 17.x.x
    repository: https://charts.bitnami.com/bitnami
  - name: mongodb
    version: 13.x.x
    repository: https://charts.bitnami.com/bitnami
  - name: kafka
    version: 22.x.x
    repository: https://charts.bitnami.com/bitnami
  - name: prometheus
    version: 23.x.x
    repository: https://prometheus-community.github.io/helm-charts
  - name: grafana
    version: 6.x.x
    repository: https://grafana.github.io/helm-charts
