apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ecommerce-platform.fullname" . }}-user-service
  labels:
    {{- include "ecommerce-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: user-service
spec:
  replicas: {{ .Values.userService.replicaCount }}
  selector:
    matchLabels:
      {{- include "ecommerce-platform.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: user-service
  template:
    metadata:
      labels:
        {{- include "ecommerce-platform.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: user-service
    spec:
      containers:
      - name: user-service
        image: "{{ .Values.global.imageRegistry }}/{{ .Values.userService.image.repository }}:{{ .Values.userService.image.tag }}"
        imagePullPolicy: {{ .Values.userService.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        {{- range $key, $value := .Values.userService.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          {{- toYaml .Values.userService.resources | nindent 10 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ecommerce-platform.fullname" . }}-user-service
  labels:
    {{- include "ecommerce-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: user-service
spec:
  type: {{ .Values.userService.service.type }}
  ports:
  - port: {{ .Values.userService.service.port }}
    targetPort: {{ .Values.userService.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "ecommerce-platform.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: user-service

{{- if .Values.userService.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
